### ISSUE TITLE
生成器的日期时间类型转换可以增加一个配置吗？

### ISSUE THREAD

**Issue by LastLighter** [mybatis-mapper/rui#3]
我尝试用Rui生成一个model实体类，但是我数据库中字段用的是datetime类型，而生成的java实体类字段是Date。但是我其实不想用Date，想使用LocalDateTime作为java的日期时间类，配置文档中找了很久也没有看到类似的配置，只好自己修改。

**Comment by abel533** [comment]
可以配置：
```yaml
database: # 1. 数据库配置，配置结构参考 io.mybatis.rui.template.database.Database
  typeMap: # 类型转换配置，覆盖默认值，默认配置请看 io.mybatis.rui.model.JdbcType
    DATE: java.time.LocalDateTime
```
